=begin pod

=head1 NAME

B<App::T2PDF - Provides program C<t2pdf>, a simple text-to-pdf converter

=head1 SYNOPSIS

=begin code :lang<raku>

use App::T2PDF;

=end code

=head1 DESCRIPTION

Module B<App::T2PDF> provides a program, named C<t2pdf>, to transform a text file
to pdf. It requires the binary file C<ps2pdf>, provided with the B<Ghostscript> package, which is available
on most Linux hosts.

Note the module also provides the following aliases for C<t2pdf>:

=item txt2pdf
=item tscript
=item asc2pdf
=item ascript

=head1 AUTHOR

Tom Browder <tbrowder@acm.org>

=head1 COPYRIGHT AND LICENSE

Copyright 2022 Tom Browder

This library is free software; you may redistribute or modify it under the Artistic License 2.0.

=end pod
